# -*- coding: utf-8 -*-
#
# allocator documentation build configuration file, created by
# sphinx-quickstart on Sat Jul 08 07:41:14 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))

# Read project metadata from pyproject.toml
try:
    import tomllib
except ImportError:
    # For Python < 3.11, use tomli
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None
from pathlib import Path

project_root = Path(__file__).parent.parent.parent
pyproject_path = project_root / "pyproject.toml"

if pyproject_path.exists() and tomllib is not None:
    with open(pyproject_path, "rb") as f:
        pyproject_data = tomllib.load(f)
    project_metadata = pyproject_data.get("project", {})
else:
    # Fallback metadata if pyproject.toml is not found
    project_metadata = {
        "name": "allocator",
        "version": "0.2.0",
        "authors": [{"name": "Suriyan Laohaprapanon, Gaurav Sood"}]
    }


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest', 
    'sphinx.ext.napoleon',          # Google/NumPy style docstrings
    'sphinx.ext.viewcode',          # Source code links
    'myst_parser',                  # Markdown support
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    '.rst': None,
    '.md': None,
}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = project_metadata.get("name", "allocator")
copyright = u'2017, Suriyan Laohaprapanon, Gaurav Sood'
author_list = project_metadata.get("authors", [])
if author_list:
    if isinstance(author_list[0], dict):
        author = ", ".join([a.get("name", "") for a in author_list])
    else:
        author = ", ".join(author_list)
else:
    author = u'Suriyan Laohaprapanon, Gaurav Sood'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = project_metadata.get("version", "0.2.0")
# The full version, including alpha/beta/rc tags.
release = project_metadata.get("version", "0.2.0")

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# MyST parser configuration
myst_enable_extensions = [
    "deflist",        # Definition lists
    "tasklist",       # Task lists  
    "colon_fence",    # ::: code blocks
    "linkify",        # Auto-link URLs
    "substitution",   # Variable substitution
    "attrs_inline",   # Inline attributes
]

# MyST heading anchors
myst_heading_anchors = 3


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
        'donate.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'allocatordoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'allocator.tex', u'allocator Documentation',
     u'Suriyan Laohaprapanon, Gaurav Sood', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'allocator', u'allocator Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'allocator', u'allocator Documentation',
     author, 'allocator', 'One line description of project.',
     'Miscellaneous'),
]



